# Global site config
lang: en
title: "neiges"
author: "Matthieu Bosquet"
email: "matthieubosquet@gmail.com"
description: "I'm a creative web developer, some things I like should end up here ;)"
google_analytics_tracking_id: UA-20728275-2

# Collections (documents sharing a namespace and properties)
collections:
  code:
    output: true

# Defaults (scoped defaults type point to a namespace, values overrides global defaults)
defaults:
  -
    scope:
      path: ""
      type: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "code"
    values:
      layout: "code"
      category:
        - programming
  -
    scope:
      path: ""
      type: "chords"
    values:
      layout: "chords"
      description: "So much time playing music. Not a minute lost."
      category:
        - music
      tags:
        - tabs
        - tablature
