# Global site config
title: "neiges"
author: "Matthieu Bosquet"
email: "matthieubosquet@gmail.com"
description: "I'm a creative web developer, some things I like should end up here ;)"
google_analytics_tracking_id: UA-20728275-2

# Collections (documents sharing a namespace and properties)
collections:
  code:
    output: true

# Defaults (scoped defaults)
defaults:
  -
    scope:
      path: ""
      type: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "code"
    values:
      layout: "code"
