# Global site config
author: "Matthieu Bosquet"
description: "Hello, neig.es is a place to share thoughts on some of the things I'm interested in like tech, music & art. Matthieu."
email: "matthieubosquet@gmail.com"
lang: "en"
title: "neiges"
google_analytics_tracking_id: UA-20728275-2

# Directory configuration
directory:
  css: "/css/"
  img: "/img/"

# Exclude from Jekyll build
exclude: ["CNAME", "Gemfile", "Gemfile.lock", "Makefile", "README.md", "/asset/css/style.css"]
