# Global site config
title: "Matthieu Bosquet"
email: "matthieubosquet@gmail.com"

# Collections (documents sharing a namespace and properties)
collections:
  code:
    output: true

# Defaults (scoped defaults)
defaults:
  -
    scope:
      path: ""
      type: "code"
    values:
      layout: "code"
